QUERY_STRING="#genomics OR #genetics OR #science OR #python OR cybersecurity OR infosec OR bitcoin OR crypto OR cryptocurrency OR monero OR  #retweet OR #like OR #follow OR #love  OR #twitter OR #repost OR #instagram OR #followme OR #share OR #tweet OR #likeforlikes OR #followback OR #k OR #likes OR #viral OR #tweets OR #likeforfollow"
HASHTAGS="#news"

INTERVAL=30
RANDOMIZATION=50
QUOTES_PERCENT=1
NEWS_PERCENT=1
REDDIT_PERCENT=1
GENOMICS_PERCENT=1
COVID19_PERCENT=1
TECHCRUNCH_PERCENT=80
TECHSTARTUP_PERCENT=10
NEWS_TOPIC='cybersecurity OR security OR infosec OR ransomware OR tech'
SUBREDDIT= 'science technology cybersecurity'
WAKETIME=5
BEDTIME=20
TIMEZONE='America/Los_Angeles'
MIN_POP=100
CHARACTER='default'
MODE='interval'

FOLLOW="294438257"
RESULT_TYPE="mixed"
TWITTER_LANG="en"
TWITTER_RETWEET_RATE=.1
TWITTER_SEARCH_COUNT=20
TWITTER_LIKE_RATE=1
USERNAME="@GenomeOrganizer"
USERID="294438257"
TWITTER_QUOTE_RATE=1
TWITTER_SEARCH_COUNT=1
# BEARER_TOKEN=`AAAAAAAAAAAAAAAAAAAAAIXSNwEAAAAAW7Wf5RncBEhx1pwMhVeEDQtHX2c%3DpIgtzwPNRUA1BEmJnqpHzZvJXyRwPMCp1AMBtpr0Zgc2jGYgnV`